// Copyright (c) 2026 Andrea Giannangelo
// SPDX-License-Identifier: GPL-3.0-or-later

import Foundation

/// The two names the bundled helper ships under (KTD2), and the only place
/// they are spelled. A later spike may drop one of them; every other file
/// reads these constants, so that change is one line.
public enum HostHelperNames {
    /// The server runs from this copy, so a folder-access prompt raised by a
    /// process the agent starts names AgentMenu's host rather than "tmux".
    public static let server = "AgentMenu Session Host"
    /// Attach clients run under this name, because Terminal.app's
    /// close-window check exempts a foreground process named `tmux` and would
    /// otherwise ask before every close.
    public static let client = "tmux"
    /// Both, in the order they are copied.
    public static let all = [server, client]
}

/// How a terminal tab attaches to a hosted session (KTD6).
///
/// iTerm uses the same plain attach as Terminal.app: its native `-CC`
/// integration is not used. The enum exists so that could be added later
/// without reshaping the callers; today it has one case.
public enum HostAttachStyle: Equatable, Sendable {
    case plain
}

/// The tmux configuration AgentMenu's server runs with (KTD5), generated here
/// rather than shipped as a resource so it is versioned with the code that
/// depends on it and needs no copy step in the bundle script. Written into the
/// host directory by `SessionHost.ensureHost()` and passed to every
/// invocation with `-f`, which replaces `~/.tmux.conf` and `/etc/tmux.conf`
/// entirely (R17: the user's own tmux setup is never read).
///
/// The point of every line is that tmux is invisible: the tab looks and
/// behaves like the terminal the agent would have run in anyway.
public enum HostConfig {
    /// The file name inside the host directory.
    public static let fileName = "tmux.conf"

    /// Bump when `contents` changes in a way a running server cannot adopt
    /// by itself. Informational: `ensureHost()` rewrites the file whenever
    /// its bytes differ, and a running server keeps the config it started
    /// with until it restarts.
    public static let revision = 1

    public static var contents: String {
        """
        # AgentMenu session host. Generated by AgentMenu (revision \(revision)); edits are overwritten.
        # Replaces ~/.tmux.conf and /etc/tmux.conf entirely: the server is started with -f.

        # The server exits only when AgentMenu kills it or it crashes, so a
        # vanished server always means an abnormal death.
        set -s exit-empty off

        # No chrome: no status bar, and the outer terminal's own title shows
        # Claude's session title, not "tmux".
        set -g status off
        set -g set-titles on
        set -g set-titles-string '#{pane_title}'

        # Keys reach the agent untouched. Ctrl+B is Claude Code's
        # background-task key, so there is no prefix at all and the prefix
        # key table is emptied. The root-table mouse bindings stay: they are
        # what makes the wheel scroll.
        set -g prefix None
        set -g prefix2 None
        unbind-key -a -T prefix
        set -s escape-time 0
        set -s extended-keys on

        # Scrollback and selection.
        set -g mouse on
        set -g history-limit 50000
        # Terminal.app ignores OSC 52, so copying goes through the system
        # pasteboard.
        set -s copy-command pbcopy

        # Pass through what the agent and the outer terminal say to each other.
        set -g allow-passthrough on
        set -s focus-events on
        set -g bell-action any
        set -g visual-bell off
        set -g default-terminal screen-256color
        """ + "\n"
    }
}
